stages:
  - install
  - build
  - test
  - coverage
  - static_analysis
  - quality_gate
  - docker_build
  - docker_push

variables:
  VERSION: "DEV-1.1.0"
  IMAGE_NAME: "my-shop-backend"

install_dependencies:
  stage: install
  image: node:18
  script:
    - cd backend/qatu
    - npm ci
  artifacts:
    paths:
      - backend/qatu/node_modules/

build_app:
  stage: build
  image: node:18
  script:
    - cd backend/qatu
    - echo "Nada a compilar, JavaScript puro"

unit_tests:
  stage: test
  image: node:18
  script:
    - cd backend/qatu
    - npm test

test_coverage:
  stage: coverage
  image: node:18
  script:
    - cd backend/qatu
    - npm run coverage
  artifacts:
    paths:
      - backend/qatu/coverage/
    when: always

static_code_analysis:
  stage: static_analysis
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd backend/qatu
    - sonar-scanner \
      -Dsonar.host.url=$SONAR_HOST_URL \
      -Dsonar.token=$SONAR_TOKEN_BACKEND \
      -Dsonar.projectKey=testdeploy_qatu-backend

quality_gate_check:
  stage: quality_gate
  image: curlimages/curl:latest
  script:
    - echo "Verificando Quality Gate via API do SonarQube (ou usar waitForQualityGate se via Jenkins com scanner CLI)"

docker_build:
  stage: docker_build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$VERSION backend/qatu
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$VERSION
  artifacts:
    name: "docker-image-info"
    expire_in: 1 hour
    paths:
      - image_info.txt
  after_script:
    - echo "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$VERSION" > image_info.txt

docker_push:
  stage: docker_push
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  dependencies:
    - docker_build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "Imagem já está no registry do GitLab."

# ===================== Frontend Pipeline =====================

frontend_pipeline:
  stage: build
  image: node:20
  script:
    - cd frontend/qatu
    - echo "Transpilando se necessário"
    - npm install
    - npm run build || echo "Sem build necessário"

frontend_tests:
  stage: test
  image: node:20
  variables:
    CI: "true"
  before_script:
    - cd frontend/qatu
    - apt-get update -qq
    - apt-get install -y -qq wget gnupg
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
    - apt-get update -qq
    - apt-get install -y -qq google-chrome-stable
    - npm ci
  script:
    - npx ng test --watch=false --karma-config=./karma.conf.js --browsers=ChromeHeadlessCINoSandbox
  retry:
    max: 1

frontend_static_scan:
  stage: static_analysis
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend/qatu
    - sonar-scanner \
      -Dsonar.host.url=$SONAR_HOST_URL \
      -Dsonar.token=$SONAR_TOKEN_FRONTEND \
      -Dsonar.projectKey=testdeploy_my-shop-frontend

frontend_quality_gate:
  stage: quality_gate
  image: curlimages/curl:latest
  script:
    - echo "Verificando Quality Gate via API do SonarQube para o FE"

frontend_build_image:
  stage: docker_build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - cd frontend/qatu
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/frontend-qatu:$VERSION .
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/frontend-qatu:$VERSION

frontend_push_image:
  stage: docker_push
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "Imagem frontend já enviada."