version: "3.8"

services:
  # --- Aplicação backend que usa MongoDB ---
  backend:
    build:
      context: ./backend/qatu
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://database:27017/qatu
    depends_on:
      - database
    networks:
      - qatu-network

  database:
    image: mongo:latest
    container_name: database
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - qatu-network

  # --- SonarQube com PostgreSQL ---
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonardb
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - qatu-network

  sonardb:
    image: postgres:13
    container_name: sonardb
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qatu-network

networks:
  qatu-network:
    driver: bridge

volumes:
  mongo-data:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:

