version: '3.8'
services:
  backend:
    build:
      context: ./qatu 
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    networks:
      - back-end
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: senha123  
      POSTGRES_DB: nome do banco  
    networks:
      - back-end

networks:
  back-end:
    driver: bridge

volumes:
  db_data: