---
- name: Instalar Docker Engine no Ubuntu Server (sem Snap)
  hosts: localhost
  become: true
  vars:
    docker_gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
    docker_repo_url: "https://download.docker.com/linux/ubuntu"

  tasks:
    - name: Instala dependências
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        update_cache: true
      environment:
        DEBIAN_FRONTEND: "noninteractive"

    - name: Cria diretório para chaves GPG
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Adiciona chave GPG oficial do Docker
      ansible.builtin.apt_key:
        url: "{{ docker_gpg_key }}"
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Adiciona repositório oficial do Docker
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] {{ docker_repo_url }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker-ce
        update_cache: true

    - name: Instala Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present  
      environment:
        DEBIAN_FRONTEND: "noninteractive"

    - name: Configura serviço Docker
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started
        daemon_reload: true

    - name: Verifica instalação do Docker
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false

    - name: Mostra versão do Docker instalada
      ansible.builtin.debug:
        msg: "Docker instalado: {{ docker_version.stdout }}"