---
- name: Instalar Docker Engine no Ubuntu Server (sem Snap)
  hosts: all
  become: true

  tasks:
    - name: Instala dependências
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Adiciona chave GPG oficial do Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adiciona repositório oficial do Docker
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker

    - name: Atualiza cache do APT
      apt:
        update_cache: yes

    - name: Instala Docker Engine, CLI e containerd
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Garante que o serviço Docker está ativo e habilitado
      systemd:
        name: docker
        enabled: yes
        state: started
